// <auto-generated />
using CountryHotel.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CountryHotel.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220514030905_SeedingData")]
    partial class SeedingData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CountryHotel.Data.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Viet Nam",
                            ShortName = "VN"
                        },
                        new
                        {
                            Id = 2,
                            Name = "The United State of America",
                            ShortName = "USA"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Japan",
                            ShortName = "JP"
                        });
                });

            modelBuilder.Entity("CountryHotel.Data.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Hanoi",
                            CountryId = 1,
                            Name = "Hilton Hotels in Hanoi",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 2,
                            Address = "Tokyo",
                            CountryId = 3,
                            Name = "Shinagawa Prince Hotel",
                            Rating = 3.7999999999999998
                        },
                        new
                        {
                            Id = 3,
                            Address = "NewYork",
                            CountryId = 2,
                            Name = "Pod Time Square",
                            Rating = 4.2999999999999998
                        });
                });

            modelBuilder.Entity("CountryHotel.Data.Hotel", b =>
                {
                    b.HasOne("CountryHotel.Data.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });
#pragma warning restore 612, 618
        }
    }
}
